version: '3.8'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1488
      POSTGRES_DB: scalper_db
    ports:
      - "5434:5432"
    volumes:
      - scalper_pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/scalper_db
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}

volumes:
  scalper_pgdata:
